### ISSUE TITLE
component is rendered twice

### ISSUE THREAD

**Issue by lowrider-fn** [andrey-skl/react-slotify#2]
Hello, it's a very good idea to write a lib for slots, in such a fairly simple implementation.
I found a problem, the component passed by the child, and then into the slot - is rendered twice.
It would be great if this issue is resolved for the lib.

I don’t really want to give up FC and I also like slots. As always, two chairs...)

```tsx
const Fields = () => {
    useEffect(()=>{
      console.log('triggers twice');
    }, []);
    
  return <input placeholder="text" />
}

const Page = () => (
  <Modal>
    <Fields/>
  </Modal>
)

const Modal:FC = ({ children }) => (
  <Form>
    <SlotFormBody>
      { children }
    </SlotFormBody>
    
    <SlotFormBottom>
      <button type="button">Submit<\button>
    </SlotFormBottom>
  </Form>
)

 const SlotFormBody = createSlot();
 const SlotFormBottom = createSlot();

const Form:FC = ({ children }) => (
  <form>
    <>
      <SlotFormBody.Renderer childs={ children } />
      <SlotFormBottom.Renderer childs={ children } />
    </>
  </form>
)
```

**Comment by andrey-skl** [comment]
@lowrider-fn Thank you for reporting this issue!

Unfortunatelly I am not sure your example can be used as is without reconstructing some not mentioned details.

Don't you mind creating an example based on this codesandbox? https://codesandbox.io/s/keen-jackson-vo2ix?file=/src/index.js

**Comment by lowrider-fn** [comment]
sorry, all fine! My bad, thanx for fast reaction)

**Comment by andrey-skl** [comment]
@lowrider-fn  Sure, welcome)
